name = "metamethods/fuse"
version = "1.0.15"
description = "A REx: Reincarnated plugin for Ore Creation"
authors = ["metamethods"]
repository = "https://github.com/metamethods/fuse"
license = "MIT"

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
vide = { wally = "wally#aloroid/vide-with-types", version = "^0.2.7" }
