name: Release

on:
    push:
        branches:
            - master
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            # Replace the version in src/constants.luau with the version in pesde.toml
            - run: |
                  PESDE_VERSION=$(cat pesde.toml | grep -Po 'version = "\K[0-9.]*(?=")')
                  sed -i "s/VERSION = \".*\"/VERSION = \"$PESDE_VERSION\"/" src/constants.luau
            - uses: CompeyDev/setup-rokit@v0.1.2
            - run: pesde install
            - run: rojo build --output "$(cat ./pesde.toml | grep -oP 'name = \".*/\K.*(?=\")').rbxm"
            - run: echo "VERSION=$(cat pesde.toml | grep -Po 'version = "\K[0-9.]*(?=")')" >> "$GITHUB_ENV"
            - run: echo "ARTIFACTS=$(cat ./pesde.toml | grep -oP 'name = \".*/\K.*(?=\")').rbxm" >> "$GITHUB_ENV"
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: ${{ env.ARTIFACTS }}
                  tag: ${{ env.VERSION }}
