name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: actions/checkout@v4
            -   uses: ok-nick/setup-aftman@v0.4.2
            -   run: wally install
            -   run: rojo sourcemap default.project.json --output sourcemap.json
            -   run: wally-package-types --sourcemap sourcemap.json Packages/
            -   run: rojo build --output fuse.rbxm
            -   run: echo "VERSION=$(cat ./Version.txt)" >> "$GITHUB_ENV"
            -   uses: ncipollo/release-action@v1
                with: 
                    artifacts: fuse.rbxm
                    tag: ${{ env.VERSION }}